### PR TITLE
Fixed flaky tests

### LINKED ISSUE #138: Fix Flaky test
`TupletTests.testReplaceNotesFromFirstToLastInTupletWithNotesOfSameDuration` is flaky somehow. The problem is that the `notes` array is somehow empty. The following is the backtrace:

```
#6	0x0000000103418eee in Tuplet.removeNotesRecursive(at:) at /Users/kyle/dev/OpenSource/music-notation-core/Sources/Tuplet.swift:416
#7	0x00000001034173e8 in Tuplet.removeNotes(at:) at /Users/kyle/dev/OpenSource/music-notation-core/Sources/Tuplet.swift:439
#8	0x0000000103413018 in Tuplet.replaceNotes(at:with:firstNoteIndex:) at /Users/kyle/dev/OpenSource/music-notation-core/Sources/Tuplet.swift:361
#9	0x0000000103411f56 in Tuplet.replaceNotes<A>(in:with:) at /Users/kyle/dev/OpenSource/music-notation-core/Sources/Tuplet.swift:168
#10	0x00000001088a00b9 in closure #1 in TupletTests.testReplaceNotesFromFirstToLastInTupletWithNotesOfSameDuration() at /Users/kyle/dev/OpenSource/music-notation-core/Tests/MusicNotationCoreTests/TupletTests.swift:1146
#11	0x00000001088a0760 in partial apply for closure #1 in TupletTests.testReplaceNotesFromFirstToLastInTupletWithNotesOfSameDuration() ()
#12	0x00000001089e78fd in XCTestCase.assertNoErrorThrown(inFile:atLine:expression:) at /Users/kyle/dev/OpenSource/music-notation-core/Tests/MusicNotationCoreTests/TestHelpers.swift:33
#13	0x000000010889f167 in TupletTests.testReplaceNotesFromFirstToLastInTupletWithNotesOfSameDuration() at /Users/kyle/dev/OpenSource/music-notation-core/Tests/MusicNotationCoreTests/TupletTests.swift:1143
```

### PR DESCRIPTION
**Pull request by sprzenus**
Reversed indexes to remove recursively to remove from the end of the array to don't change indexes pending to removal

Closes #138

### CODE REVIEW

File: Sources/Tuplet.swift [hunk 1]
```diff
@@ -303,24 +303,15 @@ public struct Tuplet: NoteCollection {
...
         for noteCollection in notes {
-            if let tuplet = noteCollection as? Tuplet {
-                if !isValid {
-                    break
-                }
-                isValid = tuplet.validate()
+            if let tuplet = noteCollection as? Tuplet, !tuplet.validate() {
+                return false
             }
             notesTicks += noteCollection.ticks
```
Comment (drumnkyle) [inline Sources/Tuplet.swift]: It looks like this is not exactly equivalent unless I'm missing something. If this wasn't just you trying to clean up the code and rather, fixing something, let me know.

The original code looks it will still call `notesTicks += noteCollection.ticks` on the first invalid call whereas yours returns false right away.

File: Sources/Tuplet.swift [hunk 2]
```diff
@@ -405,7 +410,7 @@ public struct Tuplet: NoteCollection {
             notes[first[0]] = tuplet
         } else if first.count == 2 {
             // This is the same as the method that calls this. Should be able to be extracted into helper function
-            let tupletIndexes = Set(flatIndexes.map { $0[0] })
+            let tupletIndexes = Set(flatIndexes.map({ $0[0] })).sorted(by: { $0 > $1 })
```
Comment (drumnkyle) [inline Sources/Tuplet.swift]: Do you need to do `sorted` or can you just do `reversed()`?

File: Sources/Tuplet.swift [hunk 3]
```diff
@@ -387,6 +378,20 @@ public struct Tuplet: NoteCollection {
...
         notes[flatIndex[0]] = tuplet
     }
+    
+    private mutating func removeNotes(at flatIndexes: [[Int]]) throws {
+        let counts = Set(flatIndexes.map { $0.count })
+        let flatIndexCountGroups = counts.map { count in
+            flatIndexes.filter { flatIndex in
+                return flatIndex.count == count
+            }
+        }.sorted(by: { $0[0][0] > $1[0][0] })
```
Comment (drumnkyle) [inline Sources/Tuplet.swift]: Same as below. Do you need to sort them or are you just needing to reverse them? If the latter, you can just call `reversed()`, right?

File: Sources/Tuplet.swift (hunk 1 above)
Comment (sprzenus) [reply Sources/Tuplet.swift]: I've tried to don't change the logic here, just clean up a little bit.

I don't see a huge difference here until `notesTicks` are useless if validation failed. In previous version of the code we call break if validation failed before and then returning `false` if `!isValid`. Now I just return false, because nothing can't change the final result if validation didn't pass. Ticks matter only if `isValid` is true.

File: Sources/Tuplet.swift (hunk 2 above)
Comment (sprzenus) [reply Sources/Tuplet.swift]: I cannot just call `reversed()` because:
1. It is a Set
2. There is no claim that `flatIndexes` are sorted in ascending order.

File: Sources/Tuplet.swift (hunk 3 above)
Comment (sprzenus) [reply Sources/Tuplet.swift]: Same as the previous one

File: Sources/Tuplet.swift (hunk 2 above)
Comment (drumnkyle) [reply Sources/Tuplet.swift]: Ah yes. That makes sense. Thanks.

File: Sources/Tuplet.swift (hunk 1 above)
Comment (drumnkyle) [reply Sources/Tuplet.swift]: Ah. You're right. That code was weird before. lol. Thanks!
