### PR TITLE
Converted ticks to Decimals for more accurate counting

### LINKED ISSUE #130: Incorrect number of ticks for tuplets
We currently use an Int to measure the length of events with a fixed value of 2048 ticks per quarter note.
While this covers most cases, there are situations where the length of the notes in a tuplet cannot be represented with an integer value of ticks.
For example an eight note triplet is the length of a quarter note = 2048 ticks, and each note of the triplet is 2048/3 ticks = 682.666666.... which is currently rounded down to 682 and leads to an incorrect number of total ticks.
There is a failing test that demonstrates this: ```testCumulativeTicksBeginningOfTuplet()```

### PR DESCRIPTION
**Pull request by sprzenus**
Closes #130

### CODE REVIEW

File: Sources/Extension/Decimal+Extension.swift [hunk 1]
```diff
@@ -0,0 +1,14 @@
+//
+//  Decimal+Extension.swift
+//  MusicNotationCore
+//
+//  Created by Bartłomiej Świerad on 05/11/2019.
+//
+
+import Foundation
+
+extension Decimal {
```
Comment (drumnkyle) [inline Sources/Extension/Decimal+Extension.swift]: We shouldn’t use Decimal; can we just use Double? And then when you need an Int, just use the Int initializer? We don’t want to import Foundation.

Comment (sprzenus) [reply Sources/Extension/Decimal+Extension.swift]: Importing Foundation was just my mistake because it is imported by default in a new file. We can use Double though if it's enough accurate

File: Sources/MeasureDurationValidator.swift [hunk 2]
```diff
@@ -147,22 +147,23 @@ public enum MeasureDurationValidator {
...
         }
         return availableNotes
     }
 
-    private static func findLargestDuration(lessThan ticks: Int) -> NoteDuration {
+    private static func findLargestDuration(lessThan ticks: Double) -> NoteDuration {
         let allDurations: [NoteDuration] = [.large, .long, .doubleWhole, .whole, .half, .quarter, .eighth, .sixteenth,
                                             .thirtySecond, .sixtyFourth, .oneTwentyEighth, .twoFiftySixth]
         let allTicks = allDurations.map { $0.ticks }
+        // TODO: Move the function below to Array extension
```
Comment (drumnkyle) [inline Sources/MeasureDurationValidator.swift]: Can you file an issue and mention it here so we don’t lose track of this?
